// Test Lab: filtering and export of planned test cases (test specifications). Pure functions over the planner's output;
// nothing here executes a request. Exports never contain credentials or execution results: results live in the
// evidence package, which labels mock runs SIMULATED.
import { mdCode, mdText } from "../constitution/explore";

/** The part of a Step 2 law (testable-security-model.json `laws[]`) the plan views use. */
export interface PlanLaw {
  id: string;
  category: string;
  severity?: string;
  confidence?: string;
  title?: string;
}

/** The part of a planned test case the plan views use (see planTests in 2-test-lab/app.js). */
export interface PlannedTest {
  id: string;
  lawId: string;
  category: string;
  kind: string;
  priority: number;
  hypothesis: string;
  hypothesisSource?: string;
  given: string;
  whenText: string;
  expectText: string;
  target: { method: string; pathTemplate: string; path: string; resource?: string };
  identityId: string | null;
  mutation?: { type: string; reason?: string };
  skip?: boolean;
  steps?: { label: string; path: string; expectedDeny: boolean }[];
}

export interface TestFilter {
  lawIds?: string[];
  severities?: string[];
  confidences?: string[];
}

/** Value used for a law that carries no severity or confidence; shown as such instead of inventing one. */
export const UNRATED = "UNRATED";

const inSet = (set: string[] | undefined, v: string) => !set || set.length === 0 || set.includes(v);

export function lawIndex(laws: readonly PlanLaw[]): Map<string, PlanLaw> {
  return new Map(laws.map((l) => [l.id, l]));
}

export function filterTests(tests: readonly PlannedTest[], laws: readonly PlanLaw[], filter: TestFilter = {}): PlannedTest[] {
  const byId = lawIndex(laws);
  return tests.filter((t) => {
    const law = byId.get(t.lawId);
    return inSet(filter.lawIds, t.lawId) && inSet(filter.severities, law?.severity ?? UNRATED) && inSet(filter.confidences, law?.confidence ?? UNRATED);
  });
}

/** Distinct values of one law attribute among the laws that have tests, with the number of tests for each. */
export function filterOptions(tests: readonly PlannedTest[], laws: readonly PlanLaw[], key: "id" | "severity" | "confidence"): { value: string; tests: number }[] {
  const byId = lawIndex(laws);
  const counts = new Map<string, number>();
  for (const t of tests) {
    const law = byId.get(t.lawId);
    const v = key === "id" ? t.lawId : (law?.[key] ?? UNRATED);
    counts.set(v, (counts.get(v) ?? 0) + 1);
  }
  return [...counts].map(([value, n]) => ({ value, tests: n }));
}

export interface TestPlanContext {
  modelVersion: string | null;
  generatedAt: string;
  filter: TestFilter;
  /** The target as shown to the user when the plan was exported. */
  target: { url: string | null; registered: boolean };
  executor: "mock" | "live";
  totalTests: number;
}

const DISCLAIMER =
  "Test specifications generated by the heuristic planner from the Step 1 model. Nothing in this file was executed; it contains no results, findings or credentials. Execution results are exported separately in the evidence package, where mock runs are labelled SIMULATED.";

export interface TestPlanExport {
  format: "sentinel-x-test-plan-v1";
  basis: "specification";
  disclaimer: string;
  generatedAt: string;
  modelVersion: string | null;
  filter: TestFilter;
  target: TestPlanContext["target"] & { note: string };
  executor: TestPlanContext["executor"];
  totalTests: number;
  exportedTests: number;
  laws: PlanLaw[];
  tests: {
    id: string;
    lawId: string;
    kind: string;
    priority: number;
    executable: boolean;
    given: string;
    when: string;
    expect: string;
    request: { method: string; path: string; pathTemplate: string };
    identity: string | null;
    hypothesis: string;
    hypothesisSource: string;
    mutation: string | null;
    steps: { label: string; path: string; expected: "ALLOW" | "DENY" }[];
  }[];
}

const TARGET_NOTE = "Registration records the user's own statement of authorization; it is not independently verified.";

export function exportTestPlanJson(tests: readonly PlannedTest[], laws: readonly PlanLaw[], ctx: TestPlanContext): TestPlanExport {
  const used = new Set(tests.map((t) => t.lawId));
  return {
    format: "sentinel-x-test-plan-v1",
    basis: "specification",
    disclaimer: DISCLAIMER,
    generatedAt: ctx.generatedAt,
    modelVersion: ctx.modelVersion,
    filter: ctx.filter,
    target: { ...ctx.target, note: TARGET_NOTE },
    executor: ctx.executor,
    totalTests: ctx.totalTests,
    exportedTests: tests.length,
    laws: laws.filter((l) => used.has(l.id)).map((l) => ({ id: l.id, category: l.category, severity: l.severity ?? UNRATED, confidence: l.confidence ?? UNRATED, title: l.title ?? "" })),
    tests: tests.map((t) => ({
      id: t.id,
      lawId: t.lawId,
      kind: t.kind,
      priority: t.priority,
      executable: !t.skip,
      given: t.given,
      when: t.whenText,
      expect: t.expectText,
      request: { method: t.target.method, path: t.target.path, pathTemplate: t.target.pathTemplate },
      identity: t.identityId,
      hypothesis: t.hypothesis,
      hypothesisSource: t.hypothesisSource ?? "heuristic",
      mutation: t.mutation ? t.mutation.type : null,
      steps: (t.steps ?? []).map((s) => ({ label: s.label, path: s.path, expected: s.expectedDeny ? "DENY" : "ALLOW" })),
    })),
  };
}

function describeFilter(f: TestFilter): string {
  const parts = [
    f.lawIds?.length ? `law ${f.lawIds.join(", ")}` : "",
    f.severities?.length ? `severity ${f.severities.join(", ")}` : "",
    f.confidences?.length ? `confidence ${f.confidences.join(", ")}` : "",
  ].filter(Boolean);
  return parts.length ? parts.join("; ") : "none";
}

export function exportTestPlanMarkdown(tests: readonly PlannedTest[], laws: readonly PlanLaw[], ctx: TestPlanContext): string {
  const data = exportTestPlanJson(tests, laws, ctx);
  const out: string[] = [];
  out.push(`# Test specifications${ctx.modelVersion ? `: model ${mdText(ctx.modelVersion)}` : ""}`, "");
  out.push(`> ${DISCLAIMER}`, "");
  out.push(`- Generated: ${mdText(ctx.generatedAt)}`);
  out.push(`- Target shown: ${ctx.target.url ? mdCode(ctx.target.url) : "none"} (${ctx.target.registered ? "registered sandbox target" : "not registered"}). ${TARGET_NOTE}`);
  out.push(`- Executor selected: ${ctx.executor === "mock" ? "mock (simulated)" : "live sandbox"}`);
  out.push(`- Tests: ${tests.length} of ${ctx.totalTests} (filter: ${mdText(describeFilter(ctx.filter))})`, "");
  if (!tests.length) {
    out.push("_No test case matches the filter._", "");
    return out.join("\n");
  }
  out.push("## Laws", "", "| Law | Category | Severity | Confidence | Statement |", "|---|---|---|---|---|");
  for (const l of data.laws) out.push(`| ${mdText(l.id)} | ${mdText(l.category)} | ${mdText(l.severity ?? UNRATED)} | ${mdText(l.confidence ?? UNRATED)} | ${mdText(l.title ?? "")} |`);
  out.push("", "## Test cases", "", "| Test | Law | Kind | Priority | Request | Identity | Expect |", "|---|---|---|---|---|---|---|");
  for (const t of data.tests)
    out.push(`| ${mdText(t.id)} | ${mdText(t.lawId)} | ${mdText(t.kind)} | P${t.priority} | ${t.executable ? mdCode(`${t.request.method} ${t.request.path}`) : "manual review"} | ${t.identity ? mdCode(t.identity) : "anonymous"} | ${mdText(t.expect)} |`);
  out.push("");
  for (const t of data.tests) {
    out.push(`### ${mdText(t.id)} (${mdText(t.lawId)} · ${mdText(t.kind)})`, "");
    out.push(`- Given: ${mdText(t.given)}`, `- When: ${mdText(t.when)}`, `- Expect: ${mdText(t.expect)}`);
    out.push(`- Hypothesis (${mdText(t.hypothesisSource)}): ${mdText(t.hypothesis)}`);
    t.steps.forEach((s, i) => out.push(`  ${i + 1}. ${mdText(s.label)}: ${mdCode(s.path)} → expect ${s.expected}`));
    out.push("");
  }
  return out.join("\n");
}
